# CI.yaml --- Check Puppet module

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        puppet_version: [6, 7]

    name: Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run pdk validate
        uses: puppets-epic-show-theatre/action-pdk-validate@v1
        with:
          puppet-version: ${{ matrix.puppet_version }}

      - name: Run pdk test unit
        uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
        with:
          puppet-version: ${{ matrix.puppet_version }}
